import type { RibbonIconName } from "./ribbon_icons.ts";

export const INSERT_ICON_OVERRIDES: Record<string, RibbonIconName> = {
  "illustrations.chart": "chart",
  "illustrations.icons": "icons",
  "illustrations.pictures": "pictures",
  "illustrations.pictures.online": "onlinePictures",
  "illustrations.screenshot": "screenshot",
  "illustrations.shapes": "shapes",
  "illustrations.smartArt": "smartArt",
  "links.bookmark": "bookmark",
  "links.crossReference": "crossReference",
  "links.link": "link",
  "links.link.copy": "link",
  "links.link.open": "link",
  "links.link.remove": "unlink",
  "pages.blankPage": "blankPage",
  "pages.coverPage": "coverPage",
  "pages.pageBreak": "pageBreak",
  "pages.sectionBreak.continuous": "sectionBreak",
  "pages.sectionBreak.evenPage": "sectionBreak",
  "pages.sectionBreak.nextPage": "sectionBreak",
  "pages.sectionBreak.oddPage": "sectionBreak",
  "symbols.emoji": "emoji",
  "symbols.equation": "equation",
  "symbols.symbol": "symbol",
  "tables.drawTable": "drawTable",
  "tables.insertTable": "table",
  "tables.quickTablesStandalone": "quickTables",
  "tables.responsiveDefault": "responsiveTable",
};